const state={user:null,lang:'en',role:'user'};
const shops=[{id:1,name:'Sri Lakshmi Bakery',cat:'Bakery',address:'Main Road',phone:'9876543210',lat:11.0001,lng:77.0001,photos:[]},{id:2,name:'Local Medicals',cat:'Medical',address:'Market Road',phone:'9876501234',lat:11.001,lng:77.002,photos:[]}];
const news=[{id:1,title:'Local Area App launched',body:'Community updates, shops and jobs are now available in one place.',approved:true}];
const jobs=[{id:1,title:'Sales Assistant',company:'ABC Store',cat:'Retail',salary:'₹12,000 - ₹15,000',address:'Main Road',phone:'9876543210',approved:true}];
let saved=[];

function sendOtp(){const m=document.getElementById('mobile').value.trim();if(!/^\d{10}$/.test(m))return alert('Enter a valid 10 digit mobile number');document.getElementById('otpBox').classList.remove('hidden');alert('Demo OTP: 123456');}
function verifyOtp(){if(document.getElementById('otp').value!=='123456')return alert('Wrong OTP. Use 123456 for demo.');const m=document.getElementById('mobile').value;state.user={name:'Local User',mobile:m};state.role=m.endsWith('0000')?'admin':'user';localStorage.setItem('la_user',JSON.stringify(state));showMain();}
function showMain(){document.getElementById('login').classList.add('hidden');document.getElementById('main').classList.remove('hidden');document.getElementById('content').classList.add('hidden');document.getElementById('menuName').textContent=state.user.name;document.getElementById('menuMobile').textContent=state.user.mobile;document.getElementById('welcome').textContent=state.user.mobile;document.getElementById('shopOwnerBtn').style.display=state.role==='shop_owner'?'block':'block';renderRecent();}
function renderRecent(){document.getElementById('recentNews').innerHTML=news.filter(n=>n.approved).slice(0,3).map(n=>`<div class="card"><span class="tag">News</span><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p></div>`).join('')||'<div class="empty">No updates</div>'}
function openMenu(){document.getElementById('menu').classList.add('open');document.getElementById('shade').classList.remove('hidden')}
function closeMenu(){document.getElementById('menu').classList.remove('open');document.getElementById('shade').classList.add('hidden')}
function showSection(s){closeMenu();document.getElementById('main').classList.add('hidden');document.getElementById('content').classList.remove('hidden');const titles={shops:'Shops',news:'News',jobs:'Jobs',nearby:'Nearby',offers:'Offers',services:'Services',events:'Events',emergency:'Emergency',saved:'Saved'};document.getElementById('pageTitle').textContent=titles[s]||s;const p=document.getElementById('page');if(s==='shops'||s==='nearby')renderShops(p,s==='nearby');else if(s==='news')renderNews(p);else if(s==='jobs')renderJobs(p);else if(s==='saved')renderSaved(p);else renderGeneric(p,s);}
function goHome(){document.getElementById('content').classList.add('hidden');document.getElementById('main').classList.remove('hidden')}
function renderShops(p,nearby){p.innerHTML='<input class="search" id="shopSearch" oninput="filterShops()" placeholder="🔎 Search shops..."><div id="shopList"></div>';filterShops(nearby)}
function filterShops(){const q=(document.getElementById('shopSearch')?.value||'').toLowerCase();document.getElementById('shopList').innerHTML=shops.filter(s=>(s.name+s.cat+s.address).toLowerCase().includes(q)).map(s=>`<div class="card"><span class="tag">${esc(s.cat)}</span><h3>${esc(s.name)}</h3><p>📍 ${esc(s.address)}</p><div class="actions"><button onclick="navigate(${s.lat},${s.lng})">🧭 Navigate</button><button class="secondary" onclick="call('${s.phone}')">📞 Call</button><button class="secondary" onclick="save('shop',${s.id})">❤️ Save</button></div></div>`).join('')||'<div class="empty">No shops found</div>'}
function renderNews(p){p.innerHTML=news.filter(n=>n.approved).map(n=>`<div class="card"><span class="tag">News</span><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><div class="actions"><button class="secondary" onclick="save('news',${n.id})">❤️ Save</button><button class="secondary" onclick="comment('News')">💬 Comment</button></div></div>`).join('')||'<div class="empty">No approved news</div>'}
function renderJobs(p){p.innerHTML=jobs.filter(j=>j.approved).map(j=>`<div class="card"><span class="tag">${esc(j.cat)}</span><h3>${esc(j.title)}</h3><p><b>${esc(j.company)}</b></p><p>📍 ${esc(j.address)}<br>💰 ${esc(j.salary)}</p><div class="actions"><button onclick="call('${j.phone}')">📞 Call Now</button><button class="secondary" onclick="comment('Job')">💬 Comment</button></div></div>`).join('')||'<div class="empty">No vacancies</div>'}
function renderSaved(p){p.innerHTML='<div class="empty">Saved items will appear here.</div>'}
function renderGeneric(p,s){const data={offers:['🎁 Offers','Local shops can publish offers after admin approval.'],services:['🔧 Local Services','Find mechanics, electricians, plumbers and other services.'],events:['🎉 Events','Local events and community programs.'],emergency:['🚨 Emergency','Police, Fire, Ambulance and important local contacts.']};const x=data[s]||['',''];p.innerHTML=`<div class="card"><h2>${x[0]}</h2><p>${x[1]}</p>${s==='emergency'?'<div class="actions"><button onclick="call(112)">📞 112 Emergency</button><button class="secondary" onclick="call(108)">🚑 108 Ambulance</button></div>':''}</div>`}
function createShop(){closeMenu();document.getElementById('main').classList.add('hidden');document.getElementById('content').classList.remove('hidden');document.getElementById('pageTitle').textContent='Create Shop';document.getElementById('page').innerHTML=`<div class="form"><h2>🏪 Create Your Shop</h2><label>Shop Name</label><input id="sn" placeholder="Shop name"><label>Category</label><select id="sc"><option>Medical</option><option>Department Store</option><option>Textiles</option><option>Hardware</option><option>Hotels</option><option>Mobile Shops</option><option>Fancy Stores</option><option>Bakery</option><option>Mechanics</option><option>Other</option></select><label>Address</label><textarea id="sa" placeholder="Full address"></textarea><label>Mobile Number</label><input id="sp" inputmode="numeric" maxlength="10"><label>Attach up to 4 Photos</label><input id="sphotos" type="file" accept="image/*" multiple><label>Location</label><button onclick="getLocation()">📍 Use Current Location</button><p id="loc">Location not added</p><button onclick="saveShop()">Submit for Admin Approval</button></div>`}
let chosenLocation=null;
function getLocation(){if(!navigator.geolocation)return alert('Location not supported');navigator.geolocation.getCurrentPosition(x=>{chosenLocation={lat:x.coords.latitude,lng:x.coords.longitude};document.getElementById('loc').textContent=`${chosenLocation.lat.toFixed(5)}, ${chosenLocation.lng.toFixed(5)}`},()=>alert('Please allow location access'))}
function saveShop(){const name=document.getElementById('sn').value.trim();if(!name)return alert('Enter shop name');shops.push({id:Date.now(),name,cat:document.getElementById('sc').value,address:document.getElementById('sa').value,phone:document.getElementById('sp').value,lat:chosenLocation?.lat||11,lng:chosenLocation?.lng||77,photos:[]});alert('Shop submitted. In the demo it is added locally; production version should wait for Admin approval.');showSection('shops')}
function createNews(){closeMenu();promptForm('Create News','News title','News description',(a,b)=>{news.push({id:Date.now(),title:a,body:b,approved:false});alert('News submitted for Admin approval.');})}
function createJob(){closeMenu();promptForm('Create Vacancy','Job title','Company / job details',(a,b)=>{jobs.push({id:Date.now(),title:a,company:b,cat:'Other',salary:'Contact for salary',address:'Local Area',phone:state.user.mobile,approved:false});alert('Vacancy submitted for Admin approval.');})}
function promptForm(title,p1,p2,saveFn){document.getElementById('main').classList.add('hidden');document.getElementById('content').classList.remove('hidden');document.getElementById('pageTitle').textContent=title;document.getElementById('page').innerHTML=`<div class="form"><h2>${title}</h2><input id="a" placeholder="${p1}"><textarea id="b" placeholder="${p2}"></textarea><button onclick="window._save()">Submit for Approval</button></div>`;window._save=()=>{if(!a.value.trim())return alert('Please enter title');saveFn(a.value.trim(),b.value.trim());goHome()}}
function profile(){closeMenu();alert(`Profile\nName: ${state.user.name}\nMobile: ${state.user.mobile}`)}
function reportBug(){closeMenu();const x=prompt('Describe the problem');if(x)alert('Bug report sent to Admin in demo.')}
function comment(type){const x=prompt(`Comment on ${type}`);if(x)alert('Comment added in demo.')}
function save(type,id){saved.push({type,id});alert('Saved')}
function navigate(lat,lng){location.href=`https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}`}
function call(n){location.href=`tel:${n}`}
function toggleLang(){state.lang=state.lang==='en'?'ta':'en';alert(state.lang==='ta'?'தமிழ் மொழி தேர்வு செய்யப்பட்டது (V1 demo)':'English selected (V1 demo)')}
function openAdmin(){closeMenu();if(state.role!=='admin')return alert('Admin access only. Demo admin login: use a mobile number ending with 0000.');document.getElementById('main').classList.add('hidden');document.getElementById('content').classList.remove('hidden');document.getElementById('pageTitle').textContent='Admin Approval';document.getElementById('page').innerHTML=`<div class="card"><h2>🛡️ Admin Dashboard</h2><p>Pending Shops: ${shops.filter(x=>!x.approved).length}</p><p>Pending News: ${news.filter(x=>!x.approved).length}</p><p>Pending Jobs: ${jobs.filter(x=>!x.approved).length}</p><p>Production version will connect these approvals to Supabase with secure admin permissions.</p></div>`}
function logout(){localStorage.removeItem('la_user');location.reload()}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
(function(){const x=localStorage.getItem('la_user');if(x){Object.assign(state,JSON.parse(x));showMain()}})();
